# -*- coding: utf-8 -*-
"""Password_Strength_Checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skFlz8rH_velh5KjdfkNbTQ02Du0lanD
"""

# Password Strength Checker

def check_password_strength(password):
    # Conditions
    length_condition = len(password) >= 8
    has_upper = any(char.isupper() for char in password)
    has_lower = any(char.islower() for char in password)
    has_digit = any(char.isdigit() for char in password)
    has_special = any(not char.isalnum() for char in password) # Checks for non-alphanumeric characters

    score = 0
    if length_condition:
        score += 1
    if has_upper:
        score += 1
    if has_lower:
        score += 1
    if has_digit:
        score += 1
    if has_special:
        score += 1

    print(f"\nPassword Score: {score}/5")

    # Strength check based on score
    if score == 5:
        print("Strong Password 💪")
    elif score >= 3:
        print("Medium Password 👍")
    else:
        print("Weak Password ⚠️")

    # Suggestions
    print("\nSuggestions to improve password:")
    if not length_condition:
        print("- Use at least 8 characters")
    if not has_upper:
        print("- Add uppercase letters")
    if not has_lower:
        print("- Add lowercase letters")
    if not has_digit:
        print("- Add numbers")
    if not has_special:
        print("- Add special characters")
    print("-" * 30)

while True:
    password = input("Enter your password (or 'q' to quit): ")
    if password.lower() == 'q':
        break
    if not password:
        print("Password cannot be empty. Please try again.")
        continue
    check_password_strength(password)

print("Exiting password checker.")