# -*- coding: utf-8 -*-
"""Password_Strength_Checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skFlz8rH_velh5KjdfkNbTQ02Du0lanD
"""

# Password Strength Checker

password = input("Enter your password: ")

# Conditions
length = len(password) >= 8
has_upper = False
has_lower = False
has_digit = False
has_special = False

# Check each character
for char in password:
    if char.isupper():
        has_upper = True
    elif char.islower():
        has_lower = True
    elif char.isdigit():
        has_digit = True
    else:
        has_special = True

# Strength check
if length and has_upper and has_lower and has_digit and has_special:
    print("\nStrong Password 💪")
elif length and (has_upper or has_lower) and has_digit:
    print("\nMedium Password 👍")
else:
    print("\nWeak Password ⚠️")

# Suggestions
print("\nSuggestions to improve password:")
if not length:
    print("- Use at least 8 characters")
if not has_upper:
    print("- Add uppercase letters")
if not has_lower:
    print("- Add lowercase letters")
if not has_digit:
    print("- Add numbers")
if not has_special:
    print("- Add special characters")